name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --release
        timeout-minutes: 10

  check-targets:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc,aarch64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
      - name: Check x64
        run: cargo check --target x86_64-pc-windows-msvc
      - name: Check ARM64
        run: cargo check --target aarch64-pc-windows-msvc
